#!/bin/bash

if [[ -z ${MINICONDA_VER+x} ]]
then
    # do nothing if MINICONDA_VER is not set aka we are not in the pipeline yet.
    echo "skipping cleanup"
else
    .buildkite/scripts/cleanup.sh
fi
