#!/bin/bash

if [[ -z ${MINICONDA_VER+x} ]]
then
    # do nothing if MINICONDA_VER is not set aka we are not in the pipeline yet.
    echo "skipping setup"
else
    source buildkite/scripts/setup.sh
fi
